### ISSUE TITLE
Cambiar el nombre del paquete

### ISSUE THREAD

**Issue by ninojairo** [mateohernandezs/ProyectoRestaurante#3]
https://github.com/mateohernandezs/ProyectoRestaurante/blob/61119aac300bc40e8cb9121081ddc0dc53486f4f/src/proyectococina/IngredienteContable.java#L6

Cambiar el nombre del paquete a com.bancodebogota.fdm.proyectorestaurante

**Comment by mateohernandezs** [comment]
Done
