### ISSUE TITLE
Sugerencia: cambiar nombre del proyecto

### ISSUE THREAD

**Issue by ninojairo** [mateohernandezs/ProyectoRestaurante#4]
https://github.com/mateohernandezs/ProyectoRestaurante/blob/61119aac300bc40e8cb9121081ddc0dc53486f4f/src/proyectococina/IngredienteLiquido.java#L6

Sugerencia: Cambiar el nombre del paquete com.bancodebogota.fdm.proyectorestaurante

**Comment by mateohernandezs** [comment]
Done
